# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile CXX with /usr/bin/c++
CXX_FLAGS = -O3 -DNDEBUG   -fPIC -O3 -Wall -std=gnu++11

CXX_DEFINES = -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK

CXX_INCLUDES = -isystem /usr/local/include -isystem /usr/include/eigen3 -I/home/sung/Downloads/libnabo-1.0.6 -I/home/sung/Downloads/libpointmatcher-1.2.4/contrib/yaml-cpp-pm/include -I/home/sung/Downloads/libpointmatcher-1.2.4 -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher/DataPointsFilters -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher/DataPointsFilters/utils 

